### ISSUE TITLE
How do you install this?

### ISSUE THREAD

**Issue by Toonsie** [codecat/hoh-trainer#1]
I've been loving Heroes of Hammerwatch and saw your trainer here but would like some help! I have no idea how to install this and would appreciate any assistance with this issue, thank you so much!

**Comment by codecat** [comment]
The easiest way is directly via Steam Workshop. If you’re not using Steam, you can download the .bin file from the Releases page and put it in a “mods” folder in your game directory.

Then, in game, you clone your profile and enable the mod on it.
